# Generated by Django 3.0.2 on 2020-01-23 01:25

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('serial_number', models.CharField(db_index=True, max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('serial_number', models.CharField(max_length=20)),
                ('file', models.FileField(null=True, upload_to='')),
                ('file_name', models.CharField(max_length=100)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.Notice')),
            ],
            options={
                'db_table': 'attachment',
            },
        ),
    ]
